all:
	javac -classpath .:../lib/json-20170516.jar Deadwood.java

windows:
	javac -classpath "..\\lib\\json-20170516.jar;." Deadwood.java

clean:
	-rm *.class
	-rm model/*.class
	-rm model/loading/*.class
	-rm model/board/*.class
	-rm model/board/role/*.class
	-rm model/board/room/*.class
	-rm model/board/scene/*.class
	-rm model/player/*.class
	-rm view/*.class
	-rm view/graphics/*.class
	-rm view/graphics/loading/*.class
	-rm controller/*.class

clena: clean
