all:
	javac -cp . Deadwood.java

clean:
	rm Deadwood.class
	rm model/*.class
	rm model/loading/*.class
	rm model/board/*.class

clena:
	rm Deadwood.class
	rm model/*.class
	rm model/loading/*.class
	rm model/board/*.class